import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import UserNavbar from "@/components/layout/user/userNavbar";

// Import font Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        {/* <UserNavbar /> */}
        {children}
      </body>
    </html>
  );
}
